<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->insert(
            [
                ['currency_name' => 'United Arab Emirates dirham', 'country_code' => 'AED', 'num' => '784', 'state' => 'United Arab Emirates'],
                ['currency_name' => 'Afghani', 'country_code' => 'AFN', 'num' => '971', 'state' => 'Afghanistan'],
                ['currency_name' => 'Lek', 'country_code' => 'ALL', 'num' => '8',   'state' => 'Albania'],
                ['currency_name' => 'Armenian Dram', 'country_code' => 'AMD', 'num' => '51',  'state' => 'Armenia'],
                ['currency_name' => 'Netherlands Antillian Guilder', 'country_code' => 'ANG', 'num' => '532', 'state' => 'Netherlands Antilles'],
                ['currency_name' => 'Kwanza', 'country_code' => 'AOA', 'num' => '973', 'state' => 'Angola'],
                ['currency_name' => 'Argentine Peso', 'country_code' => 'ARS', 'num' => '32',  'state' => 'Argentina'],
                ['currency_name' => 'Australian Dollar', 'country_code' => 'AUD', 'num' => '36',  'state' => 'Australia'],
                ['currency_name' => 'Aruban Guilder', 'country_code' => 'AWG', 'num' => '533', 'state' => 'Aruba'],
                ['currency_name' => 'Azerbaijanian Manat', 'country_code' => 'AZN', 'num' => '944', 'state' => 'Azerbaijan'],
                ['currency_name' => 'Convertible Marks', 'country_code' => 'BAM', 'num' => '977', 'state' => 'Bosnia and Herzegovina'],
                ['currency_name' => 'Barbados Dollar', 'country_code' => 'BBD', 'num' => '52',  'state' => 'Barbados'],
                ['currency_name' => 'Bangladeshi Taka', 'country_code' => 'BDT', 'num' => '50',  'state' => 'Bangladesh'],
                ['currency_name' => 'Bulgarian Lev', 'country_code' => 'BGN', 'num' => '975', 'state' => 'Bulgaria'],
                ['currency_name' => 'Bahraini Dinar', 'country_code' => 'BHD', 'num' => '48',  'state' => 'Bahrain'],
                ['currency_name' => 'Burundian Franc', 'country_code' => 'BIF', 'num' => '108', 'state' => 'Burundi'],
                ['currency_name' => 'Bermudian Dollar', 'country_code' => 'BMD', 'num' => '60',  'state' => 'Bermuda'],
                ['currency_name' => 'Brunei Dollar', 'country_code' => 'BND', 'num' => '96',  'state' => 'Brunei'],
                ['currency_name' => 'Boliviano', 'country_code' => 'BOB', 'num' => '68',  'state' => 'Bolivia'],
                ['currency_name' => 'Brazilian Real', 'country_code' => 'BRL', 'num' => '986', 'state' => 'Brazil'],
                ['currency_name' => 'Bahamian Dollar', 'country_code' => 'BSD', 'num' => '44',  'state' => 'Bahamas'],
                ['currency_name' => 'Ngultrum', 'country_code' => 'BTN', 'num' => '64',  'state' => 'Bhutan'],
                ['currency_name' => 'Pula', 'country_code' => 'BWP', 'num' => '72',  'state' => 'Botswana'],
                ['currency_name' => 'Belarussian Ruble', 'country_code' => 'BYR', 'num' => '974', 'state' => 'Belarus'],
                ['currency_name' => 'Belize Dollar', 'country_code' => 'BZD', 'num' => '84',  'state' => 'Belize'],
                ['currency_name' => 'Canadian Dollar', 'country_code' => 'CAD', 'num' => '124', 'state' => 'Canada'],
                ['currency_name' => 'Franc Congolais', 'country_code' => 'CDF', 'num' => '976', 'state' => 'Democratic Republic of Congo'],
                ['currency_name' => 'Swiss Franc', 'country_code' => 'CHF', 'num' => '756', 'state' => 'Switzerland, Liechtenstein'],
                ['currency_name' => 'Chilean Peso', 'country_code' => 'CLP', 'num' => '152', 'state' => 'Chile'],
                ['currency_name' => 'Yuan Renminbi', 'country_code' => 'CNY', 'num' => '156', 'state' => 'Mainland China'],
                ['currency_name' => 'Colombian Peso', 'country_code' => 'COP', 'num' => '170', 'state' => 'Colombia'],
                ['currency_name' => 'Costa Rican Colon', 'country_code' => 'CRC', 'num' => '188', 'state' => 'Costa Rica'],
                ['currency_name' => 'Cuban Peso', 'country_code' => 'CUP', 'num' => '192', 'state' => 'Cuba'],
                ['currency_name' => 'Cape Verde Escudo', 'country_code' => 'CVE', 'num' => '132', 'state' => 'Cape Verde'],
                ['currency_name' => 'Cyprus Pound', 'country_code' => 'CYP', 'num' => '196', 'state' => 'Cyprus'],
                ['currency_name' => 'Czech Koruna', 'country_code' => 'CZK', 'num' => '203', 'state' => 'Czech Republic'],
                ['currency_name' => 'Djibouti Franc', 'country_code' => 'DJF', 'num' => '262', 'state' => 'Djibouti'],
                ['currency_name' => 'Danish Krone', 'country_code' => 'DKK', 'num' => '208', 'state' => 'Denmark'],
                ['currency_name' => 'Dominican Peso', 'country_code' => 'DOP', 'num' => '214', 'state' => 'Dominican Republic'],
                ['currency_name' => 'Algerian Dinar', 'country_code' => 'DZD', 'num' => '12',  'state' => 'Algeria'],
                ['currency_name' => 'Kroon', 'country_code' => 'EEK', 'num' => '233', 'state' => 'Estonia'],
                ['currency_name' => 'Egyptian Pound', 'country_code' => 'EGP', 'num' => '818', 'state' => 'Egypt'],
                ['currency_name' => 'Nakfa', 'country_code' => 'ERN', 'num' => '232', 'state' => 'Eritrea'],
                ['currency_name' => 'Ethiopian Birr', 'country_code' => 'ETB', 'num' => '230', 'state' => 'Ethiopia'],
                ['currency_name' => 'Euro', 'country_code' => 'EUR', 'num' => '978', 'state' => 'Eurozone'],
                ['currency_name' => 'Fiji Dollar', 'country_code' => 'FJD', 'num' => '242', 'state' => 'Fiji'],
                ['currency_name' => 'Falkland Islands Pound', 'country_code' => 'FKP', 'num' => '238', 'state' => 'Falkland Islands'],
                ['currency_name' => 'Pound Sterling', 'country_code' => 'GBP', 'num' => '826', 'state' => 'United Kingdom'],
                ['currency_name' => 'Lari', 'country_code' => 'GEL', 'num' => '981', 'state' => 'Georgia'],
                ['currency_name' => 'Cedi', 'country_code' => 'GHS', 'num' => '288', 'state' => 'Ghana'],
                ['currency_name' => 'Gibraltar pound', 'country_code' => 'GIP', 'num' => '292', 'state' => 'Gibraltar'],
                ['currency_name' => 'Dalasi', 'country_code' => 'GMD', 'num' => '270', 'state' => 'Gambia'],
                ['currency_name' => 'Guinea Franc', 'country_code' => 'GNF', 'num' => '324', 'state' => 'Guinea'],
                ['currency_name' => 'Quetzal', 'country_code' => 'GTQ', 'num' => '320', 'state' => 'Guatemala'],
                ['currency_name' => 'Guyana Dollar', 'country_code' => 'GYD', 'num' => '328', 'state' => 'Guyana'],
                ['currency_name' => 'Hong Kong Dollar', 'country_code' => 'HKD', 'num' => '344', 'state' => 'Hong Kong'],
                ['currency_name' => 'Lempira', 'country_code' => 'HNL', 'num' => '340', 'state' => 'Honduras'],
                ['currency_name' => 'Croatian Kuna', 'country_code' => 'HRK', 'num' => '191', 'state' => 'Croatia'],
                ['currency_name' => 'Haiti Gourde', 'country_code' => 'HTG', 'num' => '332', 'state' => 'Haiti'],
                ['currency_name' => 'Forint', 'country_code' => 'HUF', 'num' => '348', 'state' => 'Hungary'],
                ['currency_name' => 'Rupiah', 'country_code' => 'IDR', 'num' => '360', 'state' => 'Indonesia'],
                ['currency_name' => 'New Israeli Shekel', 'country_code' => 'ILS', 'num' => '376', 'state' => 'Israel'],
                ['currency_name' => 'Indian Rupee', 'country_code' => 'INR', 'num' => '356', 'state' => 'India'],
                ['currency_name' => 'Iraqi Dinar', 'country_code' => 'IQD', 'num' => '368', 'state' => 'Iraq'],
                ['currency_name' => 'Iranian Rial', 'country_code' => 'IRR', 'num' => '364', 'state' => 'Iran'],
                ['currency_name' => 'Iceland Krona', 'country_code' => 'ISK', 'num' => '352', 'state' => 'Iceland'],
                ['currency_name' => 'Jamaican Dollar', 'country_code' => 'JMD', 'num' => '388', 'state' => 'Jamaica'],
                ['currency_name' => 'Jordanian Dinar', 'country_code' => 'JOD', 'num' => '400', 'state' => 'Jordan'],
                ['currency_name' => 'Japanese yen', 'country_code' => 'JPY', 'num' => '392', 'state' => 'Japan'],
                ['currency_name' => 'Kenyan Shilling', 'country_code' => 'KES', 'num' => '404', 'state' => 'Kenya'],
                ['currency_name' => 'Som', 'country_code' => 'KGS', 'num' => '417', 'state' => 'Kyrgyzstan'],
                ['currency_name' => 'Riel', 'country_code' => 'KHR', 'num' => '116', 'state' => 'Cambodia'],
                ['currency_name' => 'Comoro Franc', 'country_code' => 'KMF', 'num' => '174', 'state' => 'Comoros'],
                ['currency_name' => 'North Korean Won', 'country_code' => 'KPW', 'num' => '408', 'state' => 'North Korea'],
                ['currency_name' => 'South Korean Won', 'country_code' => 'KRW', 'num' => '410', 'state' => 'South Korea'],
                ['currency_name' => 'Kuwaiti Dinar', 'country_code' => 'KWD', 'num' => '414', 'state' => 'Kuwait'],
                ['currency_name' => '', 'country_code' => '',    'num' => '',    'state' => ''],
                ['currency_name' => 'Cayman Islands Dollar', 'country_code' => 'KYD', 'num' => '136', 'state' => 'Cayman Islands'],
                ['currency_name' => 'Tenge', 'country_code' => 'KZT', 'num' => '398', 'state' => 'Kazakhstan'],
                ['currency_name' => 'Kip', 'country_code' => 'LAK', 'num' => '418', 'state' => 'Laos'],
                ['currency_name' => 'Lebanese Pound', 'country_code' => 'LBP', 'num' => '422', 'state' => 'Lebanon'],
                ['currency_name' => 'Sri Lanka Rupee', 'country_code' => 'LKR', 'num' => '144', 'state' => 'Sri Lanka'],
                ['currency_name' => 'Liberian Dollar', 'country_code' => 'LRD', 'num' => '430', 'state' => 'Liberia'],
                ['currency_name' => 'Loti', 'country_code' => 'LSL', 'num' => '426', 'state' => 'Lesotho'],
                ['currency_name' => 'Lithuanian Litas', 'country_code' => 'LTL', 'num' => '440', 'state' => 'Lithuania'],
                ['currency_name' => 'Latvian Lats', 'country_code' => 'LVL', 'num' => '428', 'state' => 'Latvia'],
                ['currency_name' => 'Libyan Dinar', 'country_code' => 'LYD', 'num' => '434', 'state' => 'Libya'],
                ['currency_name' => 'Moroccan Dirham', 'country_code' => 'MAD', 'num' => '504', 'state' => 'Morocco'],
                ['currency_name' => 'Moldovan Leu', 'country_code' => 'MDL', 'num' => '498', 'state' => 'Moldova'],
                ['currency_name' => 'Malagasy Ariary', 'country_code' => 'MGA', 'num' => '969', 'state' => 'Madagascar'],
                ['currency_name' => 'Denar', 'country_code' => 'MKD', 'num' => '807', 'state' => 'Former Yugoslav Republic of Macedonia'],
                ['currency_name' => 'Kyat', 'country_code' => 'MMK', 'num' => '104', 'state' => 'Myanmar'],
                ['currency_name' => 'Tugrik', 'country_code' => 'MNT', 'num' => '496', 'state' => 'Mongolia'],
                ['currency_name' => 'Pataca', 'country_code' => 'MOP', 'num' => '446', 'state' => 'Macau'],
                ['currency_name' => 'Ouguiya', 'country_code' => 'MRO', 'num' => '478', 'state' => 'Mauritania'],
                ['currency_name' => 'Maltese Lira', 'country_code' => 'MTL', 'num' => '470', 'state' => 'Malta'],
                ['currency_name' => 'Mauritius Rupee', 'country_code' => 'MUR', 'num' => '480', 'state' => 'Mauritius'],
                ['currency_name' => 'Rufiyaa', 'country_code' => 'MVR', 'num' => '462', 'state' => 'Maldives'],
                ['currency_name' => 'Kwacha', 'country_code' => 'MWK', 'num' => '454', 'state' => 'Malawi'],
                ['currency_name' => 'Mexican Peso', 'country_code' => 'MXN', 'num' => '484', 'state' => 'Mexico'],
                ['currency_name' => 'Malaysian Ringgit', 'country_code' => 'MYR', 'num' => '458', 'state' => 'Malaysia'],
                ['currency_name' => 'Metical', 'country_code' => 'MZN', 'num' => '943', 'state' => 'Mozambique'],
                ['currency_name' => 'Namibian Dollar', 'country_code' => 'NAD', 'num' => '516', 'state' => 'Namibia'],
                ['currency_name' => 'Naira', 'country_code' => 'NGN', 'num' => '566', 'state' => 'Nigeria'],
                ['currency_name' => 'Cordoba Oro', 'country_code' => 'NIO', 'num' => '558', 'state' => 'Nicaragua'],
                ['currency_name' => 'Norwegian Krone', 'country_code' => 'NOK', 'num' => '578', 'state' => 'Norway'],
                ['currency_name' => 'Nepalese Rupee', 'country_code' => 'NPR', 'num' => '524', 'state' => 'Nepal'],
                ['currency_name' => 'New Zealand Dollar', 'country_code' => 'NZD', 'num' => '554', 'state' => 'New Zealand'],
                ['currency_name' => 'Rial Omani', 'country_code' => 'OMR', 'num' => '512', 'state' => 'Oman'],
                ['currency_name' => 'Balboa', 'country_code' => 'PAB', 'num' => '590', 'state' => 'Panama'],
                ['currency_name' => 'Nuevo Sol', 'country_code' => 'PEN', 'num' => '604', 'state' => 'Peru'],
                ['currency_name' => 'Kina', 'country_code' => 'PGK', 'num' => '598', 'state' => 'Papua New Guinea'],
                ['currency_name' => 'Philippine Peso', 'country_code' => 'PHP', 'num' => '608', 'state' => 'Philippines'],
                ['currency_name' => 'Pakistan Rupee', 'country_code' => 'PKR', 'num' => '586', 'state' => 'Pakistan'],
                ['currency_name' => 'Zloty', 'country_code' => 'PLN', 'num' => '985', 'state' => 'Poland'],
                ['currency_name' => 'Guarani', 'country_code' => 'PYG', 'num' => '600', 'state' => 'Paraguay'],
                ['currency_name' => 'Qatari Rial', 'country_code' => 'QAR', 'num' => '634', 'state' => 'Qatar'],
                ['currency_name' => 'Romanian New Leu', 'country_code' => 'RON', 'num' => '946', 'state' => 'Romania'],
                ['currency_name' => 'Serbian Dinar', 'country_code' => 'RSD', 'num' => '941', 'state' => 'Serbia'],
                ['currency_name' => 'Russian Ruble', 'country_code' => 'RUB', 'num' => '643', 'state' => 'Russia'],
                ['currency_name' => 'Rwanda Franc', 'country_code' => 'RWF', 'num' => '646', 'state' => 'Rwanda'],
                ['currency_name' => 'Saudi Riyal', 'country_code' => 'SAR', 'num' => '682', 'state' => 'Saudi Arabia'],
                ['currency_name' => 'Solomon Islands Dollar', 'country_code' => 'SBD', 'num' => '90',  'state' => 'Solomon Islands'],
                ['currency_name' => 'Seychelles Rupee', 'country_code' => 'SCR', 'num' => '690', 'state' => 'Seychelles'],
                ['currency_name' => 'Sudanese Pound', 'country_code' => 'SDG', 'num' => '938', 'state' => 'Sudan'],
                ['currency_name' => 'Swedish Krona', 'country_code' => 'SEK', 'num' => '752', 'state' => 'Sweden'],
                ['currency_name' => 'Singapore Dollar', 'country_code' => 'SGD', 'num' => '702', 'state' => 'Singapore'],
                ['currency_name' => 'Saint Helena Pound', 'country_code' => 'SHP', 'num' => '654', 'state' => 'Saint Helena'],
                ['currency_name' => 'Slovak Koruna', 'country_code' => 'SKK', 'num' => '703', 'state' => 'Slovakia'],
                ['currency_name' => 'Leone', 'country_code' => 'SLL', 'num' => '694', 'state' => 'Sierra Leone'],
                ['currency_name' => 'Somali Shilling', 'country_code' => 'SOS', 'num' => '706', 'state' => 'Somalia'],
                ['currency_name' => 'Surinam Dollar', 'country_code' => 'SRD', 'num' => '968', 'state' => 'Suriname'],
                ['currency_name' => 'Dobra', 'country_code' => 'STD', 'num' => '678', 'state' => 'Sao Tome and Príncipe'],
                ['currency_name' => 'Syrian Pound', 'country_code' => 'SYP', 'num' => '760', 'state' => 'Syria'],
                ['currency_name' => 'Lilangeni', 'country_code' => 'SZL', 'num' => '748', 'state' => 'Swaziland'],
                ['currency_name' => 'Baht', 'country_code' => 'THB', 'num' => '764', 'state' => 'Thailand'],
                ['currency_name' => 'Somoni', 'country_code' => 'TJS', 'num' => '972', 'state' => 'Tajikistan'],
                ['currency_name' => 'Manat', 'country_code' => 'TMM', 'num' => '795', 'state' => 'Turkmenistan'],
                ['currency_name' => 'Tunisian Dinar', 'country_code' => 'TND', 'num' => '788', 'state' => 'Tunisia'],
                ['currency_name' => 'Pa\'anga', 'country_code' => 'TOP', 'num' => '776', 'state' => 'Tonga'],
                ['currency_name' => 'New Turkish Lira', 'country_code' => 'TRY', 'num' => '949', 'state' => 'Turkey'],
                ['currency_name' => 'Trinidad and Tobago Dollar', 'country_code' => 'TTD', 'num' => '780', 'state' => 'Trinidad and Tobago'],
                ['currency_name' => 'New Taiwan Dollar', 'country_code' => 'TWD', 'num' => '901', 'state' => 'Taiwan'],
                ['currency_name' => 'Tanzanian Shilling', 'country_code' => 'TZS', 'num' => '834', 'state' => 'Tanzania'],
                ['currency_name' => 'Hryvnia', 'country_code' => 'UAH', 'num' => '980', 'state' => 'Ukraine'],
                ['currency_name' => 'Uganda Shilling', 'country_code' => 'UGX', 'num' => '800', 'state' => 'Uganda'],
                ['currency_name' => 'US Dollar', 'country_code' => 'USD', 'num' => '840', 'state' => 'United States of America'],
                ['currency_name' => 'Peso Uruguayo', 'country_code' => 'UYU', 'num' => '858', 'state' => 'Uruguay'],
                ['currency_name' => 'Uzbekistan Som', 'country_code' => 'UZS', 'num' => '860', 'state' => 'Uzbekistan'],
                ['currency_name' => 'Venezuelan bolívar', 'country_code' => 'VEB', 'num' => '862', 'state' => 'Venezuela'],
                ['currency_name' => 'Vietnamese dong', 'country_code' => 'VND', 'num' => '704', 'state' => 'Vietnam'],
                ['currency_name' => 'Vatu', 'country_code' => 'VUV', 'num' => '548', 'state' => 'Vanuatu'],
                ['currency_name' => 'Samoan Tala', 'country_code' => 'WST', 'num' => '882', 'state' => 'Samoa'],
                ['currency_name' => 'CFA Franc BEAC', 'country_code' => 'XAF', 'num' => '950', 'state' => 'Cameroon, Central African Republic, Congo, Chad, Equatorial Guinea, Gabon'],
                ['currency_name' => 'Silver (one Troy ounce)', 'country_code' => 'XAG', 'num' => '961', 'state' => ''],
                ['currency_name' => 'Gold (one Troy ounce)', 'country_code' => 'XAU', 'num' => '959', 'state' => ''],
                ['currency_name' => 'CFA Franc BCEAO', 'country_code' => 'XOF', 'num' => '952', 'state' => 'Benin, Burkina Faso, Cote d\'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo'],
                ['currency_name' => 'Palladium (one Troy ounce)', 'country_code' => 'XPD', 'num' => '964', 'state' => ''],
                ['currency_name' => 'CFP franc', 'country_code' => 'XPF', 'num' => '953', 'state' => 'French Polynesia, New Caledonia, Wallis and Futuna'],
                ['currency_name' => 'Platinum (one Troy ounce)', 'country_code' => 'XPT', 'num' => '962', 'state' => ''],
                ['currency_name' => 'Yemeni Rial', 'country_code' => 'YER', 'num' => '886', 'state' => 'Yemen'],
                ['currency_name' => 'South African Rand', 'country_code' => 'ZAR', 'num' => '710', 'state' => 'South Africa'],
                ['currency_name' => 'Kwacha', 'country_code' => 'ZMK', 'num' => '894', 'state' => 'Zambia'],
                ['currency_name' => 'Zimbabwe Dollar', 'country_code' => 'ZWD', 'num' => '716', 'state' => 'Zimbabwe'],

            ]
        );
    }
}
