<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TimeZonesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('timezones')->insert(
            [
                ['country_code' => 'AF', 'gmt_offset' => 'GMT +04:30', 'country_name' => 'Afghanistan', 'time_zone' => 'Asia/Kabul'],
                ['country_code' => 'AL', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Albania', 'time_zone' => 'Europe/Tirane'],
                ['country_code' => 'DZ', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Algeria', 'time_zone' => 'Africa/Algiers'],
                ['country_code' => 'AS', 'gmt_offset' => 'GMT -11:00', 'country_name' => 'American Samoa', 'time_zone' => 'Pacific/Pago_Pago'],
                ['country_code' => 'AD', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Andorra', 'time_zone' => 'Europe/Andorra'],
                ['country_code' => 'AO', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Angola', 'time_zone' => 'Africa/Luanda'],
                ['country_code' => 'AI', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Anguilla', 'time_zone' => 'America/Anguilla'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Casey'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Davis'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/DumontDUrville'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Mawson'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/McMurdo'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Palmer'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Rothera'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Syowa'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Troll'],
                ['country_code' => 'AQ', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'Antarctica', 'time_zone' => 'Antarctica/Vostok'],
                ['country_code' => 'AG', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Antigua and Barbuda', 'time_zone' => 'America/Antigua'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Buenos_Aires'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Catamarca'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Cordoba'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Jujuy'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/La_Rioja'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Mendoza'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Rio_Gallegos'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Salta'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/San_Juan'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/San_Luis'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Tucuman'],
                ['country_code' => 'AR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Argentina', 'time_zone' => 'America/Argentina/Ushuaia'],
                ['country_code' => 'AM', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Armenia', 'time_zone' => 'Asia/Yerevan'],
                ['country_code' => 'AW', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Aruba', 'time_zone' => 'America/Aruba'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Australia', 'time_zone' => 'Antarctica/Macquarie'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +09:30', 'country_name' => 'Australia', 'time_zone' => 'Australia/Adelaide'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Australia', 'time_zone' => 'Australia/Brisbane'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +09:30', 'country_name' => 'Australia', 'time_zone' => 'Australia/Broken_Hill'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Australia', 'time_zone' => 'Australia/Currie'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +09:30', 'country_name' => 'Australia', 'time_zone' => 'Australia/Darwin'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +08:45', 'country_name' => 'Australia', 'time_zone' => 'Australia/Eucla'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Australia', 'time_zone' => 'Australia/Hobart'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Australia', 'time_zone' => 'Australia/Lindeman'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +10:30', 'country_name' => 'Australia', 'time_zone' => 'Australia/Lord_Howe'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Australia', 'time_zone' => 'Australia/Melbourne'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Australia', 'time_zone' => 'Australia/Perth'],
                ['country_code' => 'AU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Australia', 'time_zone' => 'Australia/Sydney'],
                ['country_code' => 'AT', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Austria', 'time_zone' => 'Europe/Vienna'],
                ['country_code' => 'AZ', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Azerbaijan', 'time_zone' => 'Asia/Baku'],
                ['country_code' => 'BS', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Bahamas', 'time_zone' => 'America/Nassau'],
                ['country_code' => 'BH', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Bahrain', 'time_zone' => 'Asia/Bahrain'],
                ['country_code' => 'BD', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'Bangladesh', 'time_zone' => 'Asia/Dhaka'],
                ['country_code' => 'BB', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Barbados', 'time_zone' => 'America/Barbados'],
                ['country_code' => 'BY', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Belarus', 'time_zone' => 'Europe/Minsk'],
                ['country_code' => 'BE', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Belgium', 'time_zone' => 'Europe/Brussels'],
                ['country_code' => 'BZ', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Belize', 'time_zone' => 'America/Belize'],
                ['country_code' => 'BJ', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Benin', 'time_zone' => 'Africa/Porto-Novo'],
                ['country_code' => 'BM', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Bermuda', 'time_zone' => 'Atlantic/Bermuda'],
                ['country_code' => 'BT', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'Bhutan', 'time_zone' => 'Asia/Thimphu'],
                ['country_code' => 'BO', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Bolivia, Plurinational State of', 'time_zone' => 'America/La_Paz'],
                ['country_code' => 'BQ', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Bonaire, Sint Eustatius and Saba', 'time_zone' => 'America/Kralendijk'],
                ['country_code' => 'BA', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Bosnia and Herzegovina', 'time_zone' => 'Europe/Sarajevo'],
                ['country_code' => 'BW', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Botswana', 'time_zone' => 'Africa/Gaborone'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Araguaina'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Bahia'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Belem'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Boa_Vista'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Campo_Grande'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Cuiaba'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Eirunepe'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Fortaleza'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Maceio'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Manaus'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -02:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Noronha'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Porto_Velho'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Recife'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Rio_Branco'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Santarem'],
                ['country_code' => 'BR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Brazil', 'time_zone' => 'America/Sao_Paulo'],
                ['country_code' => 'IO', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'British Indian Ocean Territory', 'time_zone' => 'Indian/Chagos'],
                ['country_code' => 'BN', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Brunei Darussalam', 'time_zone' => 'Asia/Brunei'],
                ['country_code' => 'BG', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Bulgaria', 'time_zone' => 'Europe/Sofia'],
                ['country_code' => 'BF', 'gmt_offset' => 'GMT', 'country_name' => 'Burkina Faso', 'time_zone' => 'Africa/Ouagadougou'],
                ['country_code' => 'BI', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Burundi', 'time_zone' => 'Africa/Bujumbura'],
                ['country_code' => 'KH', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Cambodia', 'time_zone' => 'Asia/Phnom_Penh'],
                ['country_code' => 'CM', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Cameroon', 'time_zone' => 'Africa/Douala'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Canada', 'time_zone' => 'America/Atikokan'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Canada', 'time_zone' => 'America/Blanc-Sablon'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Canada', 'time_zone' => 'America/Cambridge_Bay'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Canada', 'time_zone' => 'America/Creston'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Canada', 'time_zone' => 'America/Dawson'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Canada', 'time_zone' => 'America/Dawson_Creek'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Canada', 'time_zone' => 'America/Edmonton'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Canada', 'time_zone' => 'America/Fort_Nelson'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Canada', 'time_zone' => 'America/Glace_Bay'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Canada', 'time_zone' => 'America/Goose_Bay'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Canada', 'time_zone' => 'America/Halifax'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Canada', 'time_zone' => 'America/Inuvik'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Canada', 'time_zone' => 'America/Iqaluit'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Canada', 'time_zone' => 'America/Moncton'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Canada', 'time_zone' => 'America/Nipigon'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Canada', 'time_zone' => 'America/Pangnirtung'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Canada', 'time_zone' => 'America/Rainy_River'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Canada', 'time_zone' => 'America/Rankin_Inlet'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Canada', 'time_zone' => 'America/Regina'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Canada', 'time_zone' => 'America/Resolute'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -02:30', 'country_name' => 'Canada', 'time_zone' => 'America/St_Johns'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Canada', 'time_zone' => 'America/Swift_Current'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Canada', 'time_zone' => 'America/Thunder_Bay'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Canada', 'time_zone' => 'America/Toronto'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Canada', 'time_zone' => 'America/Vancouver'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Canada', 'time_zone' => 'America/Whitehorse'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Canada', 'time_zone' => 'America/Winnipeg'],
                ['country_code' => 'CA', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Canada', 'time_zone' => 'America/Yellowknife'],
                ['country_code' => 'CV', 'gmt_offset' => 'GMT -01:00', 'country_name' => 'Cape Verde', 'time_zone' => 'Atlantic/Cape_Verde'],
                ['country_code' => 'KY', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Cayman Islands', 'time_zone' => 'America/Cayman'],
                ['country_code' => 'CF', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Central African Republic', 'time_zone' => 'Africa/Bangui'],
                ['country_code' => 'TD', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Chad', 'time_zone' => 'Africa/Ndjamena'],
                ['country_code' => 'CL', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Chile', 'time_zone' => 'America/Punta_Arenas'],
                ['country_code' => 'CL', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Chile', 'time_zone' => 'America/Santiago'],
                ['country_code' => 'CL', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Chile', 'time_zone' => 'Pacific/Easter'],
                ['country_code' => 'CN', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'China', 'time_zone' => 'Asia/Shanghai'],
                ['country_code' => 'CN', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'China', 'time_zone' => 'Asia/Urumqi'],
                ['country_code' => 'CX', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Christmas Island', 'time_zone' => 'Indian/Christmas'],
                ['country_code' => 'CC', 'gmt_offset' => 'GMT +06:30', 'country_name' => 'Cocos (Keeling) Islands', 'time_zone' => 'Indian/Cocos'],
                ['country_code' => 'CO', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Colombia', 'time_zone' => 'America/Bogota'],
                ['country_code' => 'KM', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Comoros', 'time_zone' => 'Indian/Comoro'],
                ['country_code' => 'CG', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Congo', 'time_zone' => 'Africa/Brazzaville'],
                ['country_code' => 'CD', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Congo, the Democratic Republic of the', 'time_zone' => 'Africa/Kinshasa'],
                ['country_code' => 'CD', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Congo, the Democratic Republic of the', 'time_zone' => 'Africa/Lubumbashi'],
                ['country_code' => 'CK', 'gmt_offset' => 'GMT -10:00', 'country_name' => 'Cook Islands', 'time_zone' => 'Pacific/Rarotonga'],
                ['country_code' => 'CR', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Costa Rica', 'time_zone' => 'America/Costa_Rica'],
                ['country_code' => 'HR', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Croatia', 'time_zone' => 'Europe/Zagreb'],
                ['country_code' => 'CU', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Cuba', 'time_zone' => 'America/Havana'],
                ['country_code' => 'CW', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Curaçao', 'time_zone' => 'America/Curacao'],
                ['country_code' => 'CY', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Cyprus', 'time_zone' => 'Asia/Famagusta'],
                ['country_code' => 'CY', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Cyprus', 'time_zone' => 'Asia/Nicosia'],
                ['country_code' => 'CZ', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Czech Republic', 'time_zone' => 'Europe/Prague'],
                ['country_code' => 'CI', 'gmt_offset' => 'GMT', 'country_name' => 'Côte d\'Ivoire', 'time_zone' => 'Africa/Abidjan'],
                ['country_code' => 'DK', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Denmark', 'time_zone' => 'Europe/Copenhagen'],
                ['country_code' => 'DJ', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Djibouti', 'time_zone' => 'Africa/Djibouti'],
                ['country_code' => 'DM', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Dominica', 'time_zone' => 'America/Dominica'],
                ['country_code' => 'DO', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Dominican Republic', 'time_zone' => 'America/Santo_Domingo'],
                ['country_code' => 'EC', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Ecuador', 'time_zone' => 'America/Guayaquil'],
                ['country_code' => 'EC', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Ecuador', 'time_zone' => 'Pacific/Galapagos'],
                ['country_code' => 'EG', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Egypt', 'time_zone' => 'Africa/Cairo'],
                ['country_code' => 'SV', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'El Salvador', 'time_zone' => 'America/El_Salvador'],
                ['country_code' => 'GQ', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Equatorial Guinea', 'time_zone' => 'Africa/Malabo'],
                ['country_code' => 'ER', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Eritrea', 'time_zone' => 'Africa/Asmara'],
                ['country_code' => 'EE', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Estonia', 'time_zone' => 'Europe/Tallinn'],
                ['country_code' => 'ET', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Ethiopia', 'time_zone' => 'Africa/Addis_Ababa'],
                ['country_code' => 'FK', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Falkland Islands (Malvinas)', 'time_zone' => 'Atlantic/Stanley'],
                ['country_code' => 'FO', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Faroe Islands', 'time_zone' => 'Atlantic/Faroe'],
                ['country_code' => 'FJ', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Fiji', 'time_zone' => 'Pacific/Fiji'],
                ['country_code' => 'FI', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Finland', 'time_zone' => 'Europe/Helsinki'],
                ['country_code' => 'FR', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'France', 'time_zone' => 'Europe/Paris'],
                ['country_code' => 'GF', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'French Guiana', 'time_zone' => 'America/Cayenne'],
                ['country_code' => 'PF', 'gmt_offset' => 'GMT -09:00', 'country_name' => 'French Polynesia', 'time_zone' => 'Pacific/Gambier'],
                ['country_code' => 'PF', 'gmt_offset' => 'GMT -09:30', 'country_name' => 'French Polynesia', 'time_zone' => 'Pacific/Marquesas'],
                ['country_code' => 'PF', 'gmt_offset' => 'GMT -10:00', 'country_name' => 'French Polynesia', 'time_zone' => 'Pacific/Tahiti'],
                ['country_code' => 'TF', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'French Southern Territories', 'time_zone' => 'Indian/Kerguelen'],
                ['country_code' => 'GA', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Gabon', 'time_zone' => 'Africa/Libreville'],
                ['country_code' => 'GM', 'gmt_offset' => 'GMT', 'country_name' => 'Gambia', 'time_zone' => 'Africa/Banjul'],
                ['country_code' => 'GE', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Georgia', 'time_zone' => 'Asia/Tbilisi'],
                ['country_code' => 'DE', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Germany', 'time_zone' => 'Europe/Berlin'],
                ['country_code' => 'DE', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Germany', 'time_zone' => 'Europe/Busingen'],
                ['country_code' => 'GH', 'gmt_offset' => 'GMT', 'country_name' => 'Ghana', 'time_zone' => 'Africa/Accra'],
                ['country_code' => 'GI', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Gibraltar', 'time_zone' => 'Europe/Gibraltar'],
                ['country_code' => 'GR', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Greece', 'time_zone' => 'Europe/Athens'],
                ['country_code' => 'GL', 'gmt_offset' => 'GMT', 'country_name' => 'Greenland', 'time_zone' => 'America/Danmarkshavn'],
                ['country_code' => 'GL', 'gmt_offset' => 'GMT -02:00', 'country_name' => 'Greenland', 'time_zone' => 'America/Nuuk'],
                ['country_code' => 'GL', 'gmt_offset' => 'GMT', 'country_name' => 'Greenland', 'time_zone' => 'America/Scoresbysund'],
                ['country_code' => 'GL', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Greenland', 'time_zone' => 'America/Thule'],
                ['country_code' => 'GD', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Grenada', 'time_zone' => 'America/Grenada'],
                ['country_code' => 'GP', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Guadeloupe', 'time_zone' => 'America/Guadeloupe'],
                ['country_code' => 'GU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Guam', 'time_zone' => 'Pacific/Guam'],
                ['country_code' => 'GT', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Guatemala', 'time_zone' => 'America/Guatemala'],
                ['country_code' => 'GG', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Guernsey', 'time_zone' => 'Europe/Guernsey'],
                ['country_code' => 'GN', 'gmt_offset' => 'GMT', 'country_name' => 'Guinea', 'time_zone' => 'Africa/Conakry'],
                ['country_code' => 'GW', 'gmt_offset' => 'GMT', 'country_name' => 'Guinea-Bissau', 'time_zone' => 'Africa/Bissau'],
                ['country_code' => 'GY', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Guyana', 'time_zone' => 'America/Guyana'],
                ['country_code' => 'HT', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Haiti', 'time_zone' => 'America/Port-au-Prince'],
                ['country_code' => 'VA', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Holy See (Vatican City State)', 'time_zone' => 'Europe/Vatican'],
                ['country_code' => 'HN', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Honduras', 'time_zone' => 'America/Tegucigalpa'],
                ['country_code' => 'HK', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Hong Kong', 'time_zone' => 'Asia/Hong_Kong'],
                ['country_code' => 'HU', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Hungary', 'time_zone' => 'Europe/Budapest'],
                ['country_code' => 'IS', 'gmt_offset' => 'GMT', 'country_name' => 'Iceland', 'time_zone' => 'Atlantic/Reykjavik'],
                ['country_code' => 'IN', 'gmt_offset' => 'GMT +05:30', 'country_name' => 'India', 'time_zone' => 'Asia/Kolkata'],
                ['country_code' => 'ID', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Indonesia', 'time_zone' => 'Asia/Jakarta'],
                ['country_code' => 'ID', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Indonesia', 'time_zone' => 'Asia/Jayapura'],
                ['country_code' => 'ID', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Indonesia', 'time_zone' => 'Asia/Makassar'],
                ['country_code' => 'ID', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Indonesia', 'time_zone' => 'Asia/Pontianak'],
                ['country_code' => 'IR', 'gmt_offset' => 'GMT +04:30', 'country_name' => 'Iran, Islamic Republic of', 'time_zone' => 'Asia/Tehran'],
                ['country_code' => 'IQ', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Iraq', 'time_zone' => 'Asia/Baghdad'],
                ['country_code' => 'IE', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Ireland', 'time_zone' => 'Europe/Dublin'],
                ['country_code' => 'IM', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Isle of Man', 'time_zone' => 'Europe/Isle_of_Man'],
                ['country_code' => 'IL', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Israel', 'time_zone' => 'Asia/Jerusalem'],
                ['country_code' => 'IT', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Italy', 'time_zone' => 'Europe/Rome'],
                ['country_code' => 'JM', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Jamaica', 'time_zone' => 'America/Jamaica'],
                ['country_code' => 'JP', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Japan', 'time_zone' => 'Asia/Tokyo'],
                ['country_code' => 'JE', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Jersey', 'time_zone' => 'Europe/Jersey'],
                ['country_code' => 'JO', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Jordan', 'time_zone' => 'Asia/Amman'],
                ['country_code' => 'KZ', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'Kazakhstan', 'time_zone' => 'Asia/Almaty'],
                ['country_code' => 'KZ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Kazakhstan', 'time_zone' => 'Asia/Aqtau'],
                ['country_code' => 'KZ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Kazakhstan', 'time_zone' => 'Asia/Aqtobe'],
                ['country_code' => 'KZ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Kazakhstan', 'time_zone' => 'Asia/Atyrau'],
                ['country_code' => 'KZ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Kazakhstan', 'time_zone' => 'Asia/Oral'],
                ['country_code' => 'KZ', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'Kazakhstan', 'time_zone' => 'Asia/Qostanay'],
                ['country_code' => 'KZ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Kazakhstan', 'time_zone' => 'Asia/Qyzylorda'],
                ['country_code' => 'KE', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Kenya', 'time_zone' => 'Africa/Nairobi'],
                ['country_code' => 'KI', 'gmt_offset' => 'GMT +13:00', 'country_name' => 'Kiribati', 'time_zone' => 'Pacific/Enderbury'],
                ['country_code' => 'KI', 'gmt_offset' => 'GMT +14:00', 'country_name' => 'Kiribati', 'time_zone' => 'Pacific/Kiritimati'],
                ['country_code' => 'KI', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Kiribati', 'time_zone' => 'Pacific/Tarawa'],
                ['country_code' => 'KP', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Korea, Democratic People\'s Republic of', 'time_zone' => 'Asia/Pyongyang'],
                ['country_code' => 'KR', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Korea, Republic of', 'time_zone' => 'Asia/Seoul'],
                ['country_code' => 'KW', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Kuwait', 'time_zone' => 'Asia/Kuwait'],
                ['country_code' => 'KG', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'Kyrgyzstan', 'time_zone' => 'Asia/Bishkek'],
                ['country_code' => 'LA', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Lao People\'s Democratic Republic', 'time_zone' => 'Asia/Vientiane'],
                ['country_code' => 'LV', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Latvia', 'time_zone' => 'Europe/Riga'],
                ['country_code' => 'LB', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Lebanon', 'time_zone' => 'Asia/Beirut'],
                ['country_code' => 'LS', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Lesotho', 'time_zone' => 'Africa/Maseru'],
                ['country_code' => 'LR', 'gmt_offset' => 'GMT', 'country_name' => 'Liberia', 'time_zone' => 'Africa/Monrovia'],
                ['country_code' => 'LY', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Libya', 'time_zone' => 'Africa/Tripoli'],
                ['country_code' => 'LI', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Liechtenstein', 'time_zone' => 'Europe/Vaduz'],
                ['country_code' => 'LT', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Lithuania', 'time_zone' => 'Europe/Vilnius'],
                ['country_code' => 'LU', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Luxembourg', 'time_zone' => 'Europe/Luxembourg'],
                ['country_code' => 'MO', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Macao', 'time_zone' => 'Asia/Macau'],
                ['country_code' => 'MK', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Macedonia, the Former Yugoslav Republic of', 'time_zone' => 'Europe/Skopje'],
                ['country_code' => 'MG', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Madagascar', 'time_zone' => 'Indian/Antananarivo'],
                ['country_code' => 'MW', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Malawi', 'time_zone' => 'Africa/Blantyre'],
                ['country_code' => 'MY', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Malaysia', 'time_zone' => 'Asia/Kuala_Lumpur'],
                ['country_code' => 'MY', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Malaysia', 'time_zone' => 'Asia/Kuching'],
                ['country_code' => 'MV', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Maldives', 'time_zone' => 'Indian/Maldives'],
                ['country_code' => 'ML', 'gmt_offset' => 'GMT', 'country_name' => 'Mali', 'time_zone' => 'Africa/Bamako'],
                ['country_code' => 'MT', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Malta', 'time_zone' => 'Europe/Malta'],
                ['country_code' => 'MH', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Marshall Islands', 'time_zone' => 'Pacific/Kwajalein'],
                ['country_code' => 'MH', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Marshall Islands', 'time_zone' => 'Pacific/Majuro'],
                ['country_code' => 'MQ', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Martinique', 'time_zone' => 'America/Martinique'],
                ['country_code' => 'MR', 'gmt_offset' => 'GMT', 'country_name' => 'Mauritania', 'time_zone' => 'Africa/Nouakchott'],
                ['country_code' => 'MU', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Mauritius', 'time_zone' => 'Indian/Mauritius'],
                ['country_code' => 'YT', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Mayotte', 'time_zone' => 'Indian/Mayotte'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Bahia_Banderas'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Cancun'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Chihuahua'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Hermosillo'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Matamoros'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Mazatlan'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Merida'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Mexico_City'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Monterrey'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Ojinaga'],
                ['country_code' => 'MX', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'Mexico', 'time_zone' => 'America/Tijuana'],
                ['country_code' => 'FM', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Micronesia, Federated States of', 'time_zone' => 'Pacific/Chuuk'],
                ['country_code' => 'FM', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Micronesia, Federated States of', 'time_zone' => 'Pacific/Kosrae'],
                ['country_code' => 'FM', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Micronesia, Federated States of', 'time_zone' => 'Pacific/Pohnpei'],
                ['country_code' => 'MD', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Moldova, Republic of', 'time_zone' => 'Europe/Chisinau'],
                ['country_code' => 'MC', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Monaco', 'time_zone' => 'Europe/Monaco'],
                ['country_code' => 'MN', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Mongolia', 'time_zone' => 'Asia/Choibalsan'],
                ['country_code' => 'MN', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Mongolia', 'time_zone' => 'Asia/Hovd'],
                ['country_code' => 'MN', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Mongolia', 'time_zone' => 'Asia/Ulaanbaatar'],
                ['country_code' => 'ME', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Montenegro', 'time_zone' => 'Europe/Podgorica'],
                ['country_code' => 'MS', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Montserrat', 'time_zone' => 'America/Montserrat'],
                ['country_code' => 'MA', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Morocco', 'time_zone' => 'Africa/Casablanca'],
                ['country_code' => 'MZ', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Mozambique', 'time_zone' => 'Africa/Maputo'],
                ['country_code' => 'MM', 'gmt_offset' => 'GMT +06:30', 'country_name' => 'Myanmar', 'time_zone' => 'Asia/Yangon'],
                ['country_code' => 'NA', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Namibia', 'time_zone' => 'Africa/Windhoek'],
                ['country_code' => 'NR', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Nauru', 'time_zone' => 'Pacific/Nauru'],
                ['country_code' => 'NP', 'gmt_offset' => 'GMT +05:45', 'country_name' => 'Nepal', 'time_zone' => 'Asia/Kathmandu'],
                ['country_code' => 'NL', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Netherlands', 'time_zone' => 'Europe/Amsterdam'],
                ['country_code' => 'NC', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'New Caledonia', 'time_zone' => 'Pacific/Noumea'],
                ['country_code' => 'NZ', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'New Zealand', 'time_zone' => 'Pacific/Auckland'],
                ['country_code' => 'NZ', 'gmt_offset' => 'GMT +12:45', 'country_name' => 'New Zealand', 'time_zone' => 'Pacific/Chatham'],
                ['country_code' => 'NI', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'Nicaragua', 'time_zone' => 'America/Managua'],
                ['country_code' => 'NE', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Niger', 'time_zone' => 'Africa/Niamey'],
                ['country_code' => 'NG', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Nigeria', 'time_zone' => 'Africa/Lagos'],
                ['country_code' => 'NU', 'gmt_offset' => 'GMT -11:00', 'country_name' => 'Niue', 'time_zone' => 'Pacific/Niue'],
                ['country_code' => 'NF', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Norfolk Island', 'time_zone' => 'Pacific/Norfolk'],
                ['country_code' => 'MP', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Northern Mariana Islands', 'time_zone' => 'Pacific/Saipan'],
                ['country_code' => 'NO', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Norway', 'time_zone' => 'Europe/Oslo'],
                ['country_code' => 'OM', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Oman', 'time_zone' => 'Asia/Muscat'],
                ['country_code' => 'PK', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Pakistan', 'time_zone' => 'Asia/Karachi'],
                ['country_code' => 'PW', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Palau', 'time_zone' => 'Pacific/Palau'],
                ['country_code' => 'PS', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Palestine, State of', 'time_zone' => 'Asia/Gaza'],
                ['country_code' => 'PS', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Palestine, State of', 'time_zone' => 'Asia/Hebron'],
                ['country_code' => 'PA', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Panama', 'time_zone' => 'America/Panama'],
                ['country_code' => 'PG', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Papua New Guinea', 'time_zone' => 'Pacific/Bougainville'],
                ['country_code' => 'PG', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Papua New Guinea', 'time_zone' => 'Pacific/Port_Moresby'],
                ['country_code' => 'PY', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Paraguay', 'time_zone' => 'America/Asuncion'],
                ['country_code' => 'PE', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'Peru', 'time_zone' => 'America/Lima'],
                ['country_code' => 'PH', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Philippines', 'time_zone' => 'Asia/Manila'],
                ['country_code' => 'PN', 'gmt_offset' => 'GMT -08:00', 'country_name' => 'Pitcairn', 'time_zone' => 'Pacific/Pitcairn'],
                ['country_code' => 'PL', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Poland', 'time_zone' => 'Europe/Warsaw'],
                ['country_code' => 'PT', 'gmt_offset' => 'GMT', 'country_name' => 'Portugal', 'time_zone' => 'Atlantic/Azores'],
                ['country_code' => 'PT', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Portugal', 'time_zone' => 'Atlantic/Madeira'],
                ['country_code' => 'PT', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Portugal', 'time_zone' => 'Europe/Lisbon'],
                ['country_code' => 'PR', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Puerto Rico', 'time_zone' => 'America/Puerto_Rico'],
                ['country_code' => 'QA', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Qatar', 'time_zone' => 'Asia/Qatar'],
                ['country_code' => 'RO', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Romania', 'time_zone' => 'Europe/Bucharest'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Anadyr'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Barnaul'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Chita'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Irkutsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Kamchatka'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Khandyga'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Krasnoyarsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Magadan'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Novokuznetsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Novosibirsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +06:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Omsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Sakhalin'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Srednekolymsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Tomsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Ust-Nera'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +10:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Vladivostok'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Yakutsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Asia/Yekaterinburg'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Astrakhan'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Kaliningrad'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Kirov'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Moscow'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Samara'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Saratov'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Ulyanovsk'],
                ['country_code' => 'RU', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Russian Federation', 'time_zone' => 'Europe/Volgograd'],
                ['country_code' => 'RW', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Rwanda', 'time_zone' => 'Africa/Kigali'],
                ['country_code' => 'RE', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Réunion', 'time_zone' => 'Indian/Reunion'],
                ['country_code' => 'BL', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Saint Barthélemy', 'time_zone' => 'America/St_Barthelemy'],
                ['country_code' => 'SH', 'gmt_offset' => 'GMT', 'country_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'time_zone' => 'Atlantic/St_Helena'],
                ['country_code' => 'KN', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Saint Kitts and Nevis', 'time_zone' => 'America/St_Kitts'],
                ['country_code' => 'LC', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Saint Lucia', 'time_zone' => 'America/St_Lucia'],
                ['country_code' => 'MF', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Saint Martin (French part)', 'time_zone' => 'America/Marigot'],
                ['country_code' => 'PM', 'gmt_offset' => 'GMT -02:00', 'country_name' => 'Saint Pierre and Miquelon', 'time_zone' => 'America/Miquelon'],
                ['country_code' => 'VC', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Saint Vincent and the Grenadines', 'time_zone' => 'America/St_Vincent'],
                ['country_code' => 'WS', 'gmt_offset' => 'GMT +13:00', 'country_name' => 'Samoa', 'time_zone' => 'Pacific/Apia'],
                ['country_code' => 'SM', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'San Marino', 'time_zone' => 'Europe/San_Marino'],
                ['country_code' => 'ST', 'gmt_offset' => 'GMT', 'country_name' => 'Sao Tome and Principe', 'time_zone' => 'Africa/Sao_Tome'],
                ['country_code' => 'SA', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Saudi Arabia', 'time_zone' => 'Asia/Riyadh'],
                ['country_code' => 'SN', 'gmt_offset' => 'GMT', 'country_name' => 'Senegal', 'time_zone' => 'Africa/Dakar'],
                ['country_code' => 'RS', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Serbia', 'time_zone' => 'Europe/Belgrade'],
                ['country_code' => 'SC', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'Seychelles', 'time_zone' => 'Indian/Mahe'],
                ['country_code' => 'SL', 'gmt_offset' => 'GMT', 'country_name' => 'Sierra Leone', 'time_zone' => 'Africa/Freetown'],
                ['country_code' => 'SG', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Singapore', 'time_zone' => 'Asia/Singapore'],
                ['country_code' => 'SX', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Sint Maarten (DGMTh part)', 'time_zone' => 'America/Lower_Princes'],
                ['country_code' => 'SK', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Slovakia', 'time_zone' => 'Europe/Bratislava'],
                ['country_code' => 'SI', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Slovenia', 'time_zone' => 'Europe/Ljubljana'],
                ['country_code' => 'SB', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Solomon Islands', 'time_zone' => 'Pacific/Guadalcanal'],
                ['country_code' => 'SO', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Somalia', 'time_zone' => 'Africa/Mogadishu'],
                ['country_code' => 'ZA', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'South Africa', 'time_zone' => 'Africa/Johannesburg'],
                ['country_code' => 'GS', 'gmt_offset' => 'GMT -02:00', 'country_name' => 'South Georgia and the South Sandwich Islands', 'time_zone' => 'Atlantic/South_Georgia'],
                ['country_code' => 'SS', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'South Sudan', 'time_zone' => 'Africa/Juba'],
                ['country_code' => 'ES', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Spain', 'time_zone' => 'Africa/Ceuta'],
                ['country_code' => 'ES', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Spain', 'time_zone' => 'Atlantic/Canary'],
                ['country_code' => 'ES', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Spain', 'time_zone' => 'Europe/Madrid'],
                ['country_code' => 'LK', 'gmt_offset' => 'GMT +05:30', 'country_name' => 'Sri Lanka', 'time_zone' => 'Asia/Colombo'],
                ['country_code' => 'SD', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Sudan', 'time_zone' => 'Africa/Khartoum'],
                ['country_code' => 'SR', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Suriname', 'time_zone' => 'America/Paramaribo'],
                ['country_code' => 'SJ', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Svalbard and Jan Mayen', 'time_zone' => 'Arctic/Longyearbyen'],
                ['country_code' => 'SZ', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Swaziland', 'time_zone' => 'Africa/Mbabane'],
                ['country_code' => 'SE', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Sweden', 'time_zone' => 'Europe/Stockholm'],
                ['country_code' => 'CH', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Switzerland', 'time_zone' => 'Europe/Zurich'],
                ['country_code' => 'SY', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Syrian Arab Republic', 'time_zone' => 'Asia/Damascus'],
                ['country_code' => 'TW', 'gmt_offset' => 'GMT +08:00', 'country_name' => 'Taiwan, Province of China', 'time_zone' => 'Asia/Taipei'],
                ['country_code' => 'TJ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Tajikistan', 'time_zone' => 'Asia/Dushanbe'],
                ['country_code' => 'TZ', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Tanzania, United Republic of', 'time_zone' => 'Africa/Dar_es_Salaam'],
                ['country_code' => 'TH', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Thailand', 'time_zone' => 'Asia/Bangkok'],
                ['country_code' => 'TL', 'gmt_offset' => 'GMT +09:00', 'country_name' => 'Timor-Leste', 'time_zone' => 'Asia/Dili'],
                ['country_code' => 'TG', 'gmt_offset' => 'GMT', 'country_name' => 'Togo', 'time_zone' => 'Africa/Lome'],
                ['country_code' => 'TK', 'gmt_offset' => 'GMT +13:00', 'country_name' => 'Tokelau', 'time_zone' => 'Pacific/Fakaofo'],
                ['country_code' => 'TO', 'gmt_offset' => 'GMT +13:00', 'country_name' => 'Tonga', 'time_zone' => 'Pacific/Tongatapu'],
                ['country_code' => 'TT', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Trinidad and Tobago', 'time_zone' => 'America/Port_of_Spain'],
                ['country_code' => 'TN', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Tunisia', 'time_zone' => 'Africa/Tunis'],
                ['country_code' => 'TR', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Turkey', 'time_zone' => 'Europe/Istanbul'],
                ['country_code' => 'TM', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Turkmenistan', 'time_zone' => 'Asia/Ashgabat'],
                ['country_code' => 'TC', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Turks and Caicos Islands', 'time_zone' => 'America/Grand_Turk'],
                ['country_code' => 'TV', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Tuvalu', 'time_zone' => 'Pacific/Funafuti'],
                ['country_code' => 'UG', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Uganda', 'time_zone' => 'Africa/Kampala'],
                ['country_code' => 'UA', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Ukraine', 'time_zone' => 'Europe/Kiev'],
                ['country_code' => 'UA', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Ukraine', 'time_zone' => 'Europe/Simferopol'],
                ['country_code' => 'UA', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Ukraine', 'time_zone' => 'Europe/Uzhgorod'],
                ['country_code' => 'UA', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Ukraine', 'time_zone' => 'Europe/Zaporozhye'],
                ['country_code' => 'AE', 'gmt_offset' => 'GMT +04:00', 'country_name' => 'United Arab Emirates', 'time_zone' => 'Asia/Dubai'],
                ['country_code' => 'GB', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'United Kingdom', 'time_zone' => 'Europe/London'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -09:00', 'country_name' => 'United States', 'time_zone' => 'America/Adak'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -08:00', 'country_name' => 'United States', 'time_zone' => 'America/Anchorage'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'United States', 'time_zone' => 'America/Boise'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'United States', 'time_zone' => 'America/Chicago'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -06:00', 'country_name' => 'United States', 'time_zone' => 'America/Denver'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Detroit'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Indianapolis'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Knox'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Marengo'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Petersburg'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Tell_City'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Vevay'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Vincennes'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Indiana/Winamac'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -08:00', 'country_name' => 'United States', 'time_zone' => 'America/Juneau'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Kentucky/Louisville'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/Kentucky/Monticello'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'United States', 'time_zone' => 'America/Los_Angeles'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'United States', 'time_zone' => 'America/Menominee'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -08:00', 'country_name' => 'United States', 'time_zone' => 'America/Metlakatla'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'United States', 'time_zone' => 'America/New_York'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -08:00', 'country_name' => 'United States', 'time_zone' => 'America/Nome'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'United States', 'time_zone' => 'America/North_Dakota/Beulah'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'United States', 'time_zone' => 'America/North_Dakota/Center'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -05:00', 'country_name' => 'United States', 'time_zone' => 'America/North_Dakota/New_Salem'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -07:00', 'country_name' => 'United States', 'time_zone' => 'America/Phoenix'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -08:00', 'country_name' => 'United States', 'time_zone' => 'America/Sitka'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -08:00', 'country_name' => 'United States', 'time_zone' => 'America/Yakutat'],
                ['country_code' => 'US', 'gmt_offset' => 'GMT -10:00', 'country_name' => 'United States', 'time_zone' => 'Pacific/Honolulu'],
                ['country_code' => 'UM', 'gmt_offset' => 'GMT -11:00', 'country_name' => 'United States Minor Outlying Islands', 'time_zone' => 'Pacific/Midway'],
                ['country_code' => 'UM', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'United States Minor Outlying Islands', 'time_zone' => 'Pacific/Wake'],
                ['country_code' => 'UY', 'gmt_offset' => 'GMT -03:00', 'country_name' => 'Uruguay', 'time_zone' => 'America/Montevideo'],
                ['country_code' => 'UZ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Uzbekistan', 'time_zone' => 'Asia/Samarkand'],
                ['country_code' => 'UZ', 'gmt_offset' => 'GMT +05:00', 'country_name' => 'Uzbekistan', 'time_zone' => 'Asia/Tashkent'],
                ['country_code' => 'VU', 'gmt_offset' => 'GMT +11:00', 'country_name' => 'Vanuatu', 'time_zone' => 'Pacific/Efate'],
                ['country_code' => 'VE', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Venezuela, Bolivarian Republic of', 'time_zone' => 'America/Caracas'],
                ['country_code' => 'VN', 'gmt_offset' => 'GMT +07:00', 'country_name' => 'Viet Nam', 'time_zone' => 'Asia/Ho_Chi_Minh'],
                ['country_code' => 'VG', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Virgin Islands, British', 'time_zone' => 'America/Tortola'],
                ['country_code' => 'VI', 'gmt_offset' => 'GMT -04:00', 'country_name' => 'Virgin Islands, U.S.', 'time_zone' => 'America/St_Thomas'],
                ['country_code' => 'WF', 'gmt_offset' => 'GMT +12:00', 'country_name' => 'Wallis and Futuna', 'time_zone' => 'Pacific/Wallis'],
                ['country_code' => 'EH', 'gmt_offset' => 'GMT +01:00', 'country_name' => 'Western Sahara', 'time_zone' => 'Africa/El_Aaiun'],
                ['country_code' => 'YE', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Yemen', 'time_zone' => 'Asia/Aden'],
                ['country_code' => 'ZM', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Zambia', 'time_zone' => 'Africa/Lusaka'],
                ['country_code' => 'ZW', 'gmt_offset' => 'GMT +02:00', 'country_name' => 'Zimbabwe', 'time_zone' => 'Africa/Harare'],
                ['country_code' => 'AX', 'gmt_offset' => 'GMT +03:00', 'country_name' => 'Åland Islands', 'time_zone' => 'Europe/Mariehamn'],
            ]
        );
    }
}
